---
- name: Create or update VLAN on Aruba AOS-CX
  hosts: aruba_cx
  gather_facts: false
  collections:
    - arubanetworks.aoscx

  # Prompt the operator at runtime
  vars_prompt:
    - name: vlan_id
      prompt: "Enter VLAN ID (1-4094)"
      private: no
      type: integer
    - name: vlan_name
      prompt: "Enter VLAN name/description"
      private: no

  pre_tasks:
    - name: Validate VLAN ID range
      assert:
        that:
          - (vlan_id | int) >= 1
          - (vlan_id | int) <= 4094
        fail_msg: "VLAN ID must be between 1 and 4094. Got {{ vlan_id }}."

  tasks:
    - name: Ensure VLAN exists
      aoscx_vlan:
        vlan_id: "{{ vlan_id | int }}"
        name: "{{ vlan_name }}"
        state: present